import Foundation

// Übersetzungen: deutscher Quelltext → [Englisch, Französisch]
// Neue Texte: L("Deutscher Text") im Code verwenden und hier ergänzen.

enum AppInfo {
    static var name: String { Bundle.main.object(forInfoDictionaryKey: "CFBundleDisplayName") as? String ?? "Aufräumer" }
    static var version: String { Bundle.main.object(forInfoDictionaryKey: "CFBundleShortVersionString") as? String ?? "1.0" }
}

enum L10n {
    static var current: String {
        let pref = UserDefaults.standard.string(forKey: "language") ?? "system"
        if pref != "system" { return pref }
        for l in Locale.preferredLanguages {
            let c = String(l.prefix(2))
            if ["de", "en", "fr"].contains(c) { return c }
        }
        return "en"
    }
    static var locale: Locale {
        switch current {
        case "de": return Locale(identifier: "de_DE")
        case "fr": return Locale(identifier: "fr_FR")
        default: return Locale(identifier: "en_US")
        }
    }
}

func L(_ key: String, _ args: CVarArg...) -> String {
    let lang = L10n.current
    let template: String
    if lang == "de" { template = key } else { template = translations[key]?[lang == "fr" ? 1 : 0] ?? key }
    return args.isEmpty ? template : String(format: template, locale: L10n.locale, arguments: args)
}

let translations: [String: [String]] = [
    "Speicher fast voll": ["Disk almost full", "Disque presque plein"],
    "Nur noch %@ frei. Öffne %@, um Platz zu schaffen.": ["Only %@ free. Open %@ to make room.", "Plus que %@ de libre. Ouvre %@ pour faire de la place."],
    "… und %d weitere": ["… and %d more", "… et %d autres"],
    "Dateien kommen in den Papierkorb. Platz wird erst frei, wenn du ihn leerst.": ["Files go to the Trash. Space is only freed once you empty it.", "Les fichiers vont dans la Corbeille. L'espace n'est libéré qu'une fois vidée."],
    "Das kann nicht rückgängig gemacht werden.": ["This cannot be undone.", "Cette action est irréversible."],
    "Analysiere Speicher …": ["Analyzing storage …", "Analyse du stockage …"],
    "Suche Caches …": ["Looking for caches …", "Recherche des caches …"],
    "Suche vendor- und node_modules-Ordner …": ["Looking for vendor and node_modules folders …", "Recherche des dossiers vendor et node_modules …"],
    "Suche SQL-Dumps …": ["Looking for SQL dumps …", "Recherche des dumps SQL …"],
    "Prüfe Docker …": ["Checking Docker …", "Vérification de Docker …"],
    "Lese Images, Container und Volumes …": ["Reading images, containers and volumes …", "Lecture des images, conteneurs et volumes …"],
    "(%d/%d) Entferne %@ …": ["(%d/%d) Removing %@ …", "(%d/%d) Suppression de %@ …"],
    "%d von %d Elementen entfernt.": ["%d of %d items removed.", "%d éléments sur %d supprimés."],
    "Im Papierkorb: ca. %@. Leere den Papierkorb, um den Platz freizugeben.": ["In the Trash: approx. %@. Empty the Trash to free the space.", "Dans la Corbeille : env. %@. Vide la Corbeille pour libérer l'espace."],
    "Freigegeben: ca. %@": ["Freed: approx. %@", "Libéré : env. %@"],
    "(sofort messbar: %@)": ["(measurable right away: %@)", "(mesurable immédiatement : %@)"],
    "Docker gibt den Platz teils verzögert an macOS zurück.": ["Docker may return the space to macOS with a delay.", "Docker rend parfois l'espace à macOS avec un peu de retard."],
    "Nicht möglich:": ["Not possible:", "Impossible :"],
    "Leere Papierkorb …": ["Emptying Trash …", "Vidage de la Corbeille …"],
    "%@ frei": ["%@ free", "%@ libres"],
    "von %@": ["of %@", "sur %@"],
    "Weniger als %d GB frei – Zeit zum Aufräumen": ["Less than %d GB free – time to clean up", "Moins de %d Go libres – il est temps de faire le ménage"],
    "Zuletzt aufgeräumt %@: %@": ["Last cleaned %@: %@", "Dernier nettoyage %@ : %@"],
    "Öffnen": ["Open", "Ouvrir"],
    "Beenden": ["Quit", "Quitter"],
    "Übersicht": ["Overview", "Aperçu"],
    "Caches": ["Caches", "Caches"],
    "Entwicklung": ["Development", "Développement"],
    "Docker": ["Docker", "Docker"],
    "Verlauf": ["History", "Historique"],
    "Einstellungen": ["Settings", "Réglages"],
    "Geschützter Pfad, nicht gelöscht: %@": ["Protected path, not deleted: %@", "Chemin protégé, non supprimé : %@"],
    "Unbekannter Fehler": ["Unknown error", "Erreur inconnue"],
    "Papierkorb konnte nicht geleert werden – bitte in Systemeinstellungen → Datenschutz → Automation den Finder erlauben.": ["Could not empty the Trash – please allow Finder under System Settings → Privacy → Automation.", "Impossible de vider la Corbeille – autorise le Finder dans Réglages Système → Confidentialité → Automatisation."],
    "Docker Desktop": ["Docker Desktop", "Docker Desktop"],
    "Images, Container und Volumes": ["Images, containers and volumes", "Images, conteneurs et volumes"],
    "Thunderbird-Mails": ["Thunderbird mail", "E-mails Thunderbird"],
    "Offline-Kopie der Postfächer – in Thunderbird unter Konto → Synchronisation & Speicherplatz begrenzen": ["Offline copy of your mailboxes – limit it in Thunderbird under Account → Synchronization & Storage", "Copie hors ligne des boîtes mail – à limiter dans Thunderbird sous Compte → Synchronisation et espace disque"],
    "Apple Mail": ["Apple Mail", "Apple Mail"],
    "App-Caches": ["App caches", "Caches des apps"],
    "Zwischenspeicher der Apps": ["Temporary app data", "Données temporaires des apps"],
    "WhatsApp-Medien": ["WhatsApp media", "Médias WhatsApp"],
    "In WhatsApp: Einstellungen → Speicher → große Dateien löschen": ["In WhatsApp: Settings → Storage → delete large files", "Dans WhatsApp : Réglages → Stockage → supprimer les gros fichiers"],
    "Claude": ["Claude", "Claude"],
    "Chrome-Profil": ["Chrome profile", "Profil Chrome"],
    "Adobe": ["Adobe", "Adobe"],
    "Slack": ["Slack", "Slack"],
    "Discord": ["Discord", "Discord"],
    "Filme": ["Movies", "Films"],
    "Downloads": ["Downloads", "Téléchargements"],
    "Selbst durchsehen – enthält oft persönliche Unterlagen": ["Review yourself – often contains personal documents", "À trier toi-même – contient souvent des documents personnels"],
    "Dokumente": ["Documents", "Documents"],
    "Schreibtisch": ["Desktop", "Bureau"],
    "Bilder": ["Pictures", "Images"],
    "iPhone-Backups": ["iPhone backups", "Sauvegardes iPhone"],
    "Finder → iPhone → Backups verwalten": ["Finder → iPhone → Manage Backups", "Finder → iPhone → Gérer les sauvegardes"],
    "Xcode / Developer": ["Xcode / Developer", "Xcode / Developer"],
    "npm-Cache": ["npm cache", "Cache npm"],
    "Projekte (%@)": ["Projects (%@)", "Projets (%@)"],
    "vendor/node_modules und SQL-Dumps": ["vendor/node_modules and SQL dumps", "vendor/node_modules et dumps SQL"],
    "Browser-Cache, baut sich automatisch neu auf": ["Browser cache, rebuilt automatically", "Cache du navigateur, se reconstruit automatiquement"],
    "Web-Cache der App (keine Chats, keine Anmeldung)": ["App web cache (no chats, no login)", "Cache web de l'app (ni discussions, ni connexion)"],
    "Paket-Downloads, werden bei Bedarf neu geladen": ["Package downloads, fetched again when needed", "Paquets téléchargés, rechargés si besoin"],
    "Heruntergeladene Test-Browser, werden bei Bedarf neu geladen": ["Downloaded test browsers, fetched again when needed", "Navigateurs de test téléchargés, rechargés si besoin"],
    "Google Chrome – Cache": ["Google Chrome – cache", "Google Chrome – cache"],
    "Firefox – Cache": ["Firefox – cache", "Firefox – cache"],
    "Brave – Cache": ["Brave – cache", "Brave – cache"],
    "Microsoft Edge – Cache": ["Microsoft Edge – cache", "Microsoft Edge – cache"],
    "Arc – Cache": ["Arc – cache", "Arc – cache"],
    "ChatGPT Atlas – Cache": ["ChatGPT Atlas – cache", "ChatGPT Atlas – cache"],
    "ChatGPT – Cache": ["ChatGPT – cache", "ChatGPT – cache"],
    "Thunderbird – Cache": ["Thunderbird – cache", "Thunderbird – cache"],
    "Nur der Cache, keine Mails": ["Cache only, no mail", "Uniquement le cache, pas les e-mails"],
    "WhatsApp – Cache": ["WhatsApp – cache", "WhatsApp – cache"],
    "CapCut – Cache": ["CapCut – cache", "CapCut – cache"],
    "Vorschau-Cache, deine Projekte bleiben": ["Preview cache, your projects stay", "Cache d'aperçu, tes projets restent"],
    "Claude – Cache": ["Claude – cache", "Claude – cache"],
    "Slack – Cache": ["Slack – cache", "Slack – cache"],
    "Discord – Cache": ["Discord – cache", "Discord – cache"],
    "VS Code – Cache": ["VS Code – cache", "VS Code – cache"],
    "Cursor – Cache": ["Cursor – cache", "Cursor – cache"],
    "npm – Cache": ["npm – cache", "npm – cache"],
    "Entspricht „npm cache clean --force“": ["Same as “npm cache clean --force”", "Équivaut à « npm cache clean --force »"],
    "Composer – Cache": ["Composer – cache", "Composer – cache"],
    "Yarn – Cache": ["Yarn – cache", "Yarn – cache"],
    "pnpm – Store": ["pnpm – store", "pnpm – store"],
    "pip – Cache": ["pip – cache", "pip – cache"],
    "Go – Build-Cache": ["Go – build cache", "Go – cache de build"],
    "Gradle – Cache": ["Gradle – cache", "Gradle – cache"],
    "CocoaPods – Cache": ["CocoaPods – cache", "CocoaPods – cache"],
    "Xcode – DerivedData": ["Xcode – DerivedData", "Xcode – DerivedData"],
    "Build-Zwischenstände, werden beim nächsten Build neu erzeugt": ["Intermediate build files, regenerated on the next build", "Fichiers de build intermédiaires, recréés au prochain build"],
    "Puppeteer – Browser": ["Puppeteer – browsers", "Puppeteer – navigateurs"],
    "Playwright – Browser": ["Playwright – browsers", "Playwright – navigateurs"],
    "shopware-cli – Cache": ["shopware-cli – cache", "shopware-cli – cache"],
    "Tool-Cache": ["Tool cache", "Cache de l'outil"],
    "Java-/JetBrains-Crash-Dumps": ["Java/JetBrains crash dumps", "Dumps de crash Java/JetBrains"],
    "Speicherabbilder nach Abstürzen (*.hprof, java_error_*.log)": ["Memory dumps after crashes (*.hprof, java_error_*.log)", "Images mémoire après plantage (*.hprof, java_error_*.log)"],
    "Absturzberichte": ["Crash reports", "Rapports de plantage"],
    "App- & Entwickler-Caches": ["App & developer caches", "Caches d'apps et de développement"],
    "Homebrew – alte Versionen & Downloads": ["Homebrew – old versions & downloads", "Homebrew – anciennes versions et téléchargements"],
    "Führt „brew cleanup --prune=all“ aus": ["Runs “brew cleanup --prune=all”", "Exécute « brew cleanup --prune=all »"],
    "Papierkorb leeren": ["Empty Trash", "Vider la Corbeille"],
    "Leert den Papierkorb über den Finder": ["Empties the Trash via Finder", "Vide la Corbeille via le Finder"],
    "Papierkorb": ["Trash", "Corbeille"],
    "Cache": ["Cache", "Cache"],
    "Logs": ["Logs", "Logs"],
    "Einstellungen & Plugins": ["Settings & plugins", "Réglages et plugins"],
    "Alte IDE-Version, aktuell ist %@": ["Old IDE version, current is %@", "Ancienne version de l'IDE, la version actuelle est %@"],
    "Nur löschen, wenn du diese Version nicht mehr brauchst": ["Only delete if you no longer need this version", "À supprimer seulement si tu n'utilises plus cette version"],
    "Alte JetBrains-Versionen": ["Old JetBrains versions", "Anciennes versions JetBrains"],
    "Abhängigkeiten ruhender Projekte (> %d Monate)": ["Dependencies of dormant projects (> %d months)", "Dépendances des projets inactifs (> %d mois)"],
    "Abhängigkeiten aktiver Projekte": ["Dependencies of active projects", "Dépendances des projets actifs"],
    "Gehört zu einem Plugin/Paket – wird eventuell zur Laufzeit gebraucht": ["Belongs to a plugin/package – may be needed at runtime", "Appartient à un plugin/paquet – peut être nécessaire à l'exécution"],
    "%@ · Projekt zuletzt geändert: %@ · wiederherstellbar mit „%@“": ["%@ · project last changed: %@ · restore with “%@”", "%@ · projet modifié le : %@ · restaurable avec « %@ »"],
    "Doppelte SQL-Dumps": ["Duplicate SQL dumps", "Dumps SQL en double"],
    "Vergleiche %@ (%@) …": ["Comparing %@ (%@) …", "Comparaison de %@ (%@) …"],
    "Identisch mit %@ (SHA-256 geprüft) – das Original bleibt": ["Identical to %@ (SHA-256 verified) – the original stays", "Identique à %@ (vérifié par SHA-256) – l'original est conservé"],
    "Große SQL-Dumps (> 1 GB) – selbst entscheiden": ["Large SQL dumps (> 1 GB) – your call", "Gros dumps SQL (> 1 Go) – à toi de décider"],
    "Dump vom %@": ["Dump from %@", "Dump du %@"],
    "Kein Duplikat – nur löschen, wenn du den Stand nicht mehr brauchst": ["Not a duplicate – only delete if you no longer need this state", "Pas un doublon – à supprimer seulement si cet état ne te sert plus"],
    "Docker ist nicht installiert": ["Docker is not installed", "Docker n'est pas installé"],
    "Images": ["Images", "Images"],
    "Container": ["Containers", "Conteneurs"],
    "Volumes": ["Volumes", "Volumes"],
    "Build-Cache": ["Build cache", "Cache de build"],
    "%@: %@ · freigebbar %@": ["%@: %@ · reclaimable %@", "%@ : %@ · récupérable %@"],
    "Gestoppte Container": ["Stopped containers", "Conteneurs arrêtés"],
    "Code und Daten im Container gehen verloren (z. B. liegt bei Dockware der Shop im Container)": ["Code and data inside the container will be lost (e.g. Dockware keeps the shop inside the container)", "Le code et les données du conteneur seront perdus (ex. : avec Dockware, la boutique est dans le conteneur)"],
    "Ungenutzte Images": ["Unused images", "Images inutilisées"],
    "<ohne Namen> %@": ["<unnamed> %@", "<sans nom> %@"],
    "kann per docker pull neu geladen werden": ["can be re-downloaded with docker pull", "peut être retéléchargée avec docker pull"],
    "verwaistes Zwischen-Image": ["dangling intermediate image", "image intermédiaire orpheline"],
    "lokal gebaut": ["built locally", "construite localement"],
    "Lokal gebaut – nur per Neubau wiederherstellbar": ["Built locally – can only be restored by rebuilding", "Construite localement – restaurable uniquement en la reconstruisant"],
    "Verwaiste Volumes": ["Orphaned volumes", "Volumes orphelins"],
    "Volume, das an keinem Container hängt": ["Volume not attached to any container", "Volume rattaché à aucun conteneur"],
    "Enthaltene Daten (z. B. Datenbanken) gehen verloren": ["Data inside (e.g. databases) will be lost", "Les données qu'il contient (ex. : bases de données) seront perdues"],
    "%d GB": ["%d GB", "%d Go"],
    "Zwischenspeicher, die sich von selbst neu aufbauen. Ist eine App geöffnet, wird ihr Cache übersprungen.": ["Temporary data that rebuilds itself. If an app is open, its cache is skipped.", "Données temporaires qui se reconstruisent seules. Si une app est ouverte, son cache est ignoré."],
    "Kein Projektordner": ["No project folder", "Aucun dossier de projets"],
    "Füge in den Einstellungen die Ordner hinzu, in denen deine Projekte liegen.": ["Add the folders that contain your projects in Settings.", "Ajoute dans les Réglages les dossiers qui contiennent tes projets."],
    "Zu den Einstellungen": ["Open Settings", "Ouvrir les Réglages"],
    "vendor/node_modules (nur mit composer.lock bzw. package.json – jederzeit wiederherstellbar) und SQL-Dumps in: %@": ["vendor/node_modules (only with composer.lock or package.json – restorable anytime) and SQL dumps in: %@", "vendor/node_modules (uniquement avec composer.lock ou package.json – restaurables à tout moment) et dumps SQL dans : %@"],
    "Bereinigung abgeschlossen": ["Cleanup complete", "Nettoyage terminé"],
    "Papierkorb jetzt leeren": ["Empty Trash now", "Vider la Corbeille maintenant"],
    "Später": ["Later", "Plus tard"],
    "Willkommen bei %@": ["Welcome to %@", "Bienvenue dans %@"],
    "Platz schaffen auf dem Mac – sicher und nachvollziehbar.": ["Free up space on your Mac – safely and transparently.", "Libère de l'espace sur ton Mac – en toute sécurité et transparence."],
    "Nichts wird ohne deine Bestätigung gelöscht. Du siehst vorher jede Datei mit Größe.": ["Nothing is deleted without your confirmation. You see every item and its size first.", "Rien n'est supprimé sans ta confirmation. Tu vois d'abord chaque élément et sa taille."],
    "Standardmäßig landet alles im Papierkorb – umstellbar in den Einstellungen.": ["By default everything goes to the Trash – you can change this in Settings.", "Par défaut, tout va dans la Corbeille – modifiable dans les Réglages."],
    "Alles bleibt auf deinem Mac. Die App sendet keine Daten.": ["Everything stays on your Mac. The app sends no data.", "Tout reste sur ton Mac. L'app n'envoie aucune donnée."],
    "Für vollständige Werte kannst du in den Einstellungen den Festplattenvollzugriff erteilen.": ["For complete numbers you can grant Full Disk Access in Settings.", "Pour des chiffres complets, tu peux accorder l'accès complet au disque dans les Réglages."],
    "Los geht's": ["Let's go", "C'est parti"],
    "%@ frei von %@": ["%@ free of %@", "%@ libres sur %@"],
    "Neu scannen": ["Rescan", "Réanalyser"],
    "Gescannt %@": ["Scanned %@", "Analysé %@"],
    "Wo dein Speicher steckt und was sich aufräumen lässt.": ["Where your storage goes and what can be cleaned up.", "Où part ton espace disque et ce qui peut être nettoyé."],
    "Frei": ["Free", "Libre"],
    "Belegt": ["Used", "Utilisé"],
    "Zum Aufräumen vorgemerkt": ["Marked for cleanup", "Sélectionné pour le nettoyage"],
    "Die Auslagerungsdatei (Swap) belegt %@. Ein Neustart des Macs gibt diesen Platz frei.": ["The swap file uses %@. Restarting your Mac frees this space.", "Le fichier d'échange (swap) occupe %@. Redémarrer le Mac libère cet espace."],
    "Größte Bereiche": ["Largest areas", "Plus gros postes"],
    "Analysiere …": ["Analyzing …", "Analyse …"],
    "Noch nicht gescannt": ["Not scanned yet", "Pas encore analysé"],
    "Im Finder zeigen": ["Show in Finder", "Afficher dans le Finder"],
    "Zu „%@“ →": ["Go to “%@” →", "Aller à « %@ » →"],
    "%@ in den Papierkorb legen?": ["Move %@ to the Trash?", "Mettre %@ à la Corbeille ?"],
    "%@ endgültig löschen?": ["Permanently delete %@?", "Supprimer définitivement %@ ?"],
    "Scanne …": ["Scanning …", "Analyse en cours …"],
    "Alles sauber": ["All clean", "Tout est propre"],
    "Hier gibt es gerade nichts aufzuräumen.": ["Nothing to clean up here right now.", "Rien à nettoyer ici pour le moment."],
    "Alle": ["All", "Tout"],
    "Keine": ["None", "Aucun"],
    "Entfernen": ["Remove", "Retirer"],
    "Löschen": ["Delete", "Supprimer"],
    "Abbrechen": ["Cancel", "Annuler"],
    "%@ ist geöffnet – App beenden und neu scannen": ["%@ is open – quit the app and rescan", "%@ est ouvert – quitte l'app et relance l'analyse"],
    "%d ausgewählt · %@": ["%d selected · %@", "%d sélectionnés · %@"],
    "Papierkorb-Modus": ["Trash mode", "Mode Corbeille"],
    "Bereinigen …": ["Clean up …", "Nettoyer …"],
    "Docker startet …": ["Docker is starting …", "Docker démarre …"],
    "Docker läuft nicht": ["Docker is not running", "Docker n'est pas lancé"],
    "Damit Images, Container und Volumes geprüft werden können, muss Docker laufen.": ["Docker must be running to check images, containers and volumes.", "Docker doit être lancé pour analyser les images, conteneurs et volumes."],
    "Docker starten": ["Start Docker", "Lancer Docker"],
    "Erneut prüfen": ["Check again", "Vérifier à nouveau"],
    "Ungenutzte Images und Build-Cache sind vorausgewählt. Container und Volumes nur, wenn du sie bewusst anhakst.": ["Unused images and build cache are preselected. Containers and volumes only if you tick them yourself.", "Les images inutilisées et le cache de build sont présélectionnés. Conteneurs et volumes seulement si tu les coches toi-même."],
    "Docker-Datei auf der Platte: %@": ["Docker disk image on disk: %@", "Fichier disque Docker : %@"],
    "Insgesamt aufgeräumt: %@": ["Cleaned up in total: %@", "Total nettoyé : %@"],
    "Noch nichts aufgeräumt": ["Nothing cleaned up yet", "Rien de nettoyé pour l'instant"],
    "Allgemein": ["General", "Général"],
    "Sprache": ["Language", "Langue"],
    "Systemsprache": ["System language", "Langue du système"],
    "Beim Bereinigen": ["When cleaning up", "Lors du nettoyage"],
    "In den Papierkorb legen (umkehrbar)": ["Move to Trash (reversible)", "Mettre à la Corbeille (réversible)"],
    "Endgültig löschen (Platz sofort frei)": ["Delete permanently (space freed immediately)", "Supprimer définitivement (espace libéré tout de suite)"],
    "Projektordner": ["Project folders", "Dossiers de projets"],
    "Noch kein Ordner – füge den Ordner hinzu, in dem deine Projekte liegen.": ["No folder yet – add the folder that contains your projects.", "Aucun dossier – ajoute le dossier qui contient tes projets."],
    "Ordner hinzufügen …": ["Add folder …", "Ajouter un dossier …"],
    "Automatisch erkennen": ["Detect automatically", "Détecter automatiquement"],
    "Projekte gelten als ruhend nach %d Monaten": ["Projects count as dormant after %d months", "Un projet est considéré inactif après %d mois"],
    "Menüleiste & Warnung": ["Menu bar & warning", "Barre des menus et alerte"],
    "Warnen, wenn weniger als %d GB frei sind": ["Warn when less than %d GB are free", "Alerter quand il reste moins de %d Go"],
    "Beim Anmelden automatisch starten": ["Launch at login", "Lancer à l'ouverture de session"],
    "Berechtigungen": ["Permissions", "Autorisations"],
    "Für vollständige Größenangaben (z. B. Mail, iPhone-Backups) braucht die App den Festplattenvollzugriff. Gelöscht wird nie etwas ohne deine Bestätigung.": ["For complete sizes (e.g. Mail, iPhone backups) the app needs Full Disk Access. Nothing is ever deleted without your confirmation.", "Pour des tailles complètes (ex. : Mail, sauvegardes iPhone), l'app a besoin de l'accès complet au disque. Rien n'est jamais supprimé sans ta confirmation."],
    "Festplattenvollzugriff öffnen …": ["Open Full Disk Access …", "Ouvrir l'accès complet au disque …"],
    "Über": ["About", "À propos"],
    "Version": ["Version", "Version"],
    "Willkommensbildschirm erneut zeigen": ["Show welcome screen again", "Revoir l'écran d'accueil"],
    "Konnte nicht geändert werden: %@": ["Could not be changed: %@", "Modification impossible : %@"],
]
